### ISSUE TITLE
ginのmiddlware で github.com/go-playground/validator の validator.ValidationErrors が拾えない問題

### ISSUE THREAD

**Issue by aazw** [aazw/go-base#1]
ginのmiddlware において、  
github.com/go-playground/validator の validator.ValidationErrors が拾えない

```go
func ProblemDetailsRenderer() gin.HandlerFunc {
	return func(c *gin.Context) {
		c.Next()

		if len(c.Errors) == 0 {
			fmt.Println("1")
			// 異常終了していない
			return
		}

		fmt.Printf("%+v\n", c.Errors.Last().Err)

		ge := c.Errors.Last() // *gin.Error
		if ge == nil {
			fmt.Println("2")
			// エラーが無ければ何もしない
			return
		}

		var verrs validator.ValidationErrors
		if errors.As(ge.Err, &verrs) {
			// ここでバリデーションエラーの結果を整形したいが、拾えない
			
		}
	}
}
```

**Comment by aazw** [comment]
https://github.com/oapi-codegen/runtime/types.ErrValidationEmail が呼ばれている模様  
https://github.com/oapi-codegen/runtime/blob/v1.1.1/types/email.go#L9

**Comment by aazw** [comment]
oapi-codegenでstructを生成していたが、もとのOpenAPIのSpecの定義で、 ` format: uuid` や `format: email` を使っていると、oapi-codegeの特殊型が使われ、バリデーション以前のjsonのUnmarshalでコケている模様.

これを外し、すべてstringとして処理させれば、 validator.ValidationErrors が捕捉できた.

```yaml
components:
  schemas:
    User:
      type: object
      description: Representation of a user
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the user (UUIDv7)
          pattern: '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-7[0-9a-fA-F]{3}-[89ABab][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$'
          minLength: 36
          maxLength: 36
          x-oapi-codegen-extra-tags:
            binding: 'required,uuid'
          # https://github.com/oapi-codegen/oapi-codegen/issues/760
          x-go-type: uuid.UUID
          x-go-type-import:
            name: uuid
            path: github.com/google/uuid
        name:
          type: string
          description: Full name of the user
          pattern: '^.+$'
          minLength: 1
          maxLength: 100
          x-oapi-codegen-extra-tags:
            binding: 'required,min=1,max=100'
        email:
          type: string
          format: email
          description: Email address of the user
          pattern: '^[^@]+@[^@]+\.[^@]+$'
          minLength: 5
          maxLength: 254
          x-oapi-codegen-extra-tags:
            binding: 'required,email,min=5,max=254'
      required:
        - id
        - name
        - email
```
